### ISSUE TITLE
AnalyticalTable: Table height of the Analytical table isn't changing on using responsivepopin

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents-react#2501]
### **Bug Description**
I am using FlexibleColumnLayout in my application, and within the startColumn of FlexibleColumnLayout, I am using an Analytical Table. On click of any row in the AnalyticalTable, the midcolumn of Flexiblecolumn must expand and the startcolumn must show analyticaltable data in cards format. I have used responsivePopin property for the columns there. The card formation and layout changes are happening smoothly only, but the table height is not changing when we're expanding the midColumn. 
Suppose startColumn has 5 rows in the analyticalTable, and suppose the height of each row is 50 right now, when we click on any row, the startColumn shrinks and midColumn expands, making the rowHeight in startColumn to say 250. In that case, the height of the table should also expand, but it remains the same as before and we have to scroll through the table to view all the data. 

### **Expected Behavior**
Instead of what is happening currently, the table height must expand according to the row height and screen height both. 

### **Steps to Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/nifty-estrela-rle9o?file=/src/App.js)
2. Click on any row in the table

### **Log Output / Stack Trace / Screenshots**
<img width="1792" alt="screenshot_2022-01-06_at_2 09 25_pm" src="https://user-images.githubusercontent.com/54435646/149896991-d3db6f72-24d6-434e-b35b-8c68b2fb9365.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by I516406** [comment]
Hi @Lukas742 

Thanks for your response. 
I am using a BusyIndicator around the Analytical Table in the FlexibleColumnLayout of my application. 
The Table fails to display all the columns properly in that case. 

Link to the sandbox - **https://codesandbox.io/s/infallible-allen-kwh3lk**

**Comment by Lukas742** [comment]
Hi @I516406 

you have to make sure, that the container of the table, or the table itself receives fixed dimensions.
See [codeSandbox](https://codesandbox.io/s/stoic-forest-bezton?file=/src/App.js)

Since the table offers a `loading` prop itself, I would recommend using it instead of the `BusyIndicator`, then you would also only have to set the `height` to the container.
See [codeSandbox](https://codesandbox.io/s/crazy-carlos-z4fccs?file=/src/App.js)

**Comment by I516406** [comment]
Hi @Lukas742  

I tried the first approach, providing fixed dimensions to the container. It works well in isolation, but when we wrap it around a DynamicPage, it behaves as earlier. 
See [codeSandbox](https://codesandbox.io/s/reverent-hopper-8bpw0e?file=/src/App.js)

In the second approach where I don't use the BusyIndicator component and instead use the AnalyticalTable loading prop, when we wrap it around a DynamicPage container, and remove the buttons that you added, it behaves as earlier.

See [codeSandbox](https://codesandbox.io/s/twilight-cdn-5hqo0w)

**Comment by Lukas742** [comment]
Hi @I516406 

I think there's no way around an observer in that case. I created a [codeSandbox](https://codesandbox.io/s/fcl-dynpage-anatable-9dzqlk) where I added some comments so it's easier to understand.

Please note, that there is currently a bug in low `AnalyticalTables` when columns are "popped in" in runtime. We already merged a [fix](https://github.com/SAP/ui5-webcomponents-react/pull/2688) though and it will be available with the next release.

**Comment by I516406** [comment]
Hi @Lukas742  

The problem with this approach is that the container height is not increasing on popin of the columns. 
A table scrollbar appears to view the data, but the requirement is to have a scrollbar for the entire dynamicPage when the PopIn happens. 
Even after the update, the bug isn't resolved.
Kindly look into this and revert back.

**Comment by Lukas742** [comment]
For me the fix seems to be working as intended, so I don't really see why we should revert the changes. Could you add a reproducible example showing that the fix isn't working?

As mentioned before, the container not increasing its height is implemented like this to prevent moving elements around due to height differences of the table when columns are popped in, so it's implemented like this by design. This [PR](https://github.com/SAP/ui5-webcomponents-react/pull/2721) will add a prop that makes it possible to control whether the table should calculate it's height solely on the base row height or also incorporate the pop-in row height.

Although I don't really understand why you would need to implement the table without it's sticky header, virtualisation, etc. it's still possible by setting `visibleRows` to a very high number like `Infinity`. With this it's possible to make the container as high as the number of rows and when the mentioned PR is released, you can also make the table calculate its body height according to it's row height (no matter if popped in or not)

**Comment by I516406** [comment]
Hi @Lukas742  

If you go to this [codeSandbox](https://codesandbox.io/s/fcl-dynpage-anatable-9dzqlk), you'll see that after clicking on any row, the columns pop in and the data is visible. 
The functional requirement that we have is to not have a sticky header. Instead we want a scrollbar for the entire container of the startColumn of the FlexibleColumnLayout after the popin happens. 
In our app, we don't have titles or headings in the header component. We just have a Filterbar component at the top, which we don't want to stick upon scrolling. 
Can you share an example on how do we achieve that here? 
Also keep in mind the following container layers - 
FlexibleColumnLayout -> DynamicPage -> Flexbox -> BusyIndicator -> AnalyticalTable. 

Regards,
Sparsh

**Comment by Lukas742** [comment]
Hi @I516406 

sorry, but I don't really get the requirement.

- Where is the FilterBar mounted?
- Why would you need a DynamicPage if you don't use the header or title section?
- Why do you need to use the BusyIndicator around the AnalyticalTable? This will cause the container to increase/decrease in height and could cause bad UX and is also not the intended way of handling the busy state of the table.

Except for the FilterBar part I tried to adjust my [example](https://codesandbox.io/s/fcl-dynpage-anatable-forked-7ir0pq?file=/src/App.js) according to your description. If this is not how you wanted it, please change it in the [codeSandbox](https://codesandbox.io/s/fcl-dynpage-anatable-forked-7ir0pq?file=/src/App.js).

**Comment by I516406** [comment]
Hi @Lukas742  

This is working correctly now. 
Actually I was using `adjustTableHeightOnPopIn` and `visibleRowCountMode='Auto'` together, which was causing issues. 
Removing all the height styles and `visibleRowCountMode='Auto'` from the code, it seems to work as expected. 

Thanks a lot for your support. 

Regards,
Sparsh
